[[allowlists]]
  description = "Allow specific secret files as they are not secrets that matter."

  paths = [
    "components/platform/users/files/users.htpasswd",
    "components/platform/users/base/htpass-secret.yaml",
    "components/platform/users/base/cluster.yaml",
    "components/platform/oauth/yaml/oauth-secret.yaml",
    "components/platform/oauth/yaml/cluster.yaml",
    "components/apps/keycloak/base/admin-secret.yaml",
    "clusters/appofapps-repository-config.yaml"
  ]
